### ISSUE TITLE
  Outdated dependency in build.xml

### ISSUE THREAD

**Issue by gallardo** [alkacon/alkacon-oamp#3]
I must obviously be missing something here. The build.xml refers to ant-opencms-1.1.jar, but the current opencms-core is being packaged with "ant-opencms-1.2.jar" (https://github.com/alkacon/opencms-core/blob/master/lib/compile/ant-opencms-1.2.jar) since at least 9 months ago!:

> mMoossen 9 months ago removed core dependencies in ant-opencms-1.2.jar.

Current build.xml doesn't compile and fails with:

> [...]/src/opencms-alkacon/alkacon-oamp/build.xml:63: Problem: failed to create task or type selectionprompt
> Cause: The name is undefined.
> Action: Check the spelling.
> Action: Check that any custom tasks/types have been declared.
> Action: Check that any <presetdef>/<macrodef> declarations have taken place.

Is anyone using this build-script?

**Comment by mathiasconradt** [comment]
@gallardo I'm wondering, why is this ticket closed? How did you resolve it? Cause I'm having the same issue right now. I need to compile the old OAMP that I used for OCMS7 against OCMS8, cause I'm updating the system.

**Comment by gallardo** [comment]
@mathiaslin My fault --I should have added a comment before closing the issue. I closed the issue because I opened a corresponding [pull request](https://github.com/alkacon/alkacon-oamp/pull/9)
