### ISSUE TITLE
Captch Webform Module 2.0.2 not working with Java 8

### ISSUE THREAD

**Issue by kartobi** [alkacon/alkacon-oamp#44]
After updating to Java 8 captcha images of webforms are completely black.

**Comment by aKandzior** [comment]
At the moment Java 8 is not officially supported by OpenCms, we recommend to use Java 7.

**Comment by kartobi** [comment]
Thanks Alexander for your quick response.
Do you plan to support Java 8 for OpenCms 10?

**Comment by aKandzior** [comment]
Yes we plan official Java 8 support for OpenCms 10. "Official" support in this case referes to our commercial support offerings. OpenCms 9.5 already works "mostly" with Java 8, but little issues like this one prevent us from "officially" supporting Java 8 at the moment.

**Comment by kartobi** [comment]
Is working now with Java8.
